---
- name: deploy java application
  get_url:
   url: http://54.187.43.161:8081/artifactory/TEST/{{buildno}}/target/mahaLogin-1.0.war
   dest: /opt/tomcat/webapps/mahaLogin.war
   username: admin
   password: password
   force_basic_auth: yes
  notify: tom restart

